/* prettier-ignore */
// @ts-nocheck
// Generated by @uni-ku/bundle-optimizer
declare module '*?async' {
  const component: any
  export = component
}
declare module '@/sub-packages/components/SubCom.vue?async' {
  const component: typeof import('@/sub-packages/components/SubCom.vue')
  export = component
}
declare module '~/sub-packages/components/SubCom.vue?async' {
  const component: typeof import('~/sub-packages/components/SubCom.vue')
  export = component
}
