/* prettier-ignore */
// @ts-nocheck
// Generated by @uni-ku/bundle-optimizer
export {}

interface ModuleMap {
  '@/sub-packages/components/SubCom.vue': typeof import('@/sub-packages/components/SubCom.vue')
  '@/sub-packages/utils/subUtils': typeof import('@/sub-packages/utils/subUtils')
  [path: string]: any
}

declare global {
  function AsyncImport<T extends keyof ModuleMap>(arg: T): Promise<ModuleMap[T]>
}
