/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IceyAvatar: typeof import('./../components/Base/IceyAvatar.vue')['default']
    LivePhoto: typeof import('./../components/LivePhoto/index.vue')['default']
    LPImage: typeof import('./../components/LPImage/index.vue')['default']
    NavBar: typeof import('./../components/NavBar/index.vue')['default']
    PrivacyPopup: typeof import('./../components/PrivacyPopup.vue')['default']
    PullDownBg: typeof import('./../components/pullDownBg.vue')['default']
    TabBar: typeof import('./../components/TabBar/index.vue')['default']
    TheFooter: typeof import('./../components/TheFooter.vue')['default']
    UpImage: typeof import('uni-ui-plus/components/image/image.vue')['default']
    WaterfallsList: typeof import('./../components/WaterfallsList.vue')['default']
  }
}
