/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  | '/pages/index'
  | '/pages/webview'
  | '/pages/home/detail'
  | '/pages/mine/index'
  | '/pages/post/index'
  | '/pages-sub/index'
  | '/sub-packages/index'

interface NavigateToOptions {
  url: _LocationUrl
}
interface RedirectToOptions extends NavigateToOptions {}

type SwitchTabOptions = {}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void
}

declare module 'virtual:uni-pages' {
  export type LocationUrl = _LocationUrl
}
